version: "3"
services:
  db:
    image: postgres:13.5
    volumes:
      - ./data_db/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"