version: "3"
services:
  bot:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 bot.py
    depends_on:
      - db

  db:
    image: postgres:13.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "bot_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwerty"
    expose:
      - 5432

  volumes:
    postgres_data:
